---
version: "3"
services:
  example:
    depends_on:
      - db
    build: .
    ports:
      - "127.0.0.1:8001:8000"
    restart: always
    environment:
      - POSTGRES_PASSWORD=lAJCH9uTkGaM8t4BHfM6c1SG
      - POSTGRES_USER=example
      - POSTGRES_DB=example
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:13.2
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=lAJCH9uTkGaM8t4BHfM6c1SG
      - POSTGRES_USER=example
      - POSTGRES_DB=example
