# Generated by Django 4.1 on 2022-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiny", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="shortcode",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
