# -*- coding: utf-8 -*-
# Generated by Django 4.1 on 2022-08-13 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0002_alter_redirect_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='last_accessed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
