
on:
  push:
    branches:
      - "master"
jobs:
  run-test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run-test-scripts
        run: ./run_tests.sh

  linters:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: Install requirements
        run: pip install -r requirements.txt

      - uses: psf/black@stable
        with:
          options: "--check --skip-string-normalization"
          src: "."
          version: "22.3.0"
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'linters'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
